Repository SKKone-blockchain/caver-py, pull requests merged in 2020-03, with the labels that each got.

#2 [feature] Accounts, account, util, accountKeyTypes
  caver/klay/account/__init__.py
  caver/klay/account/account.py
  caver/klay/accounts/__init__.py
  caver/klay/accounts/account/account.py
  caver/klay/accounts/accountKey/accountKeyMultiSig.py
  caver/klay/accounts/accountKey/accountKeyPublic.py
  caver/klay/accounts/accountKey/accountKeyRoleBase.py
  caver/klay/accounts/accountUtil/accountUtil.py
  caver/klay/accounts/accountUtil/bytes.py
  caver/klay/accounts/accountUtil/hashFunction.py
  caver/klay/accounts/accounts.py
  caver/klay/accounts/wallet/__init__.py
  caver/klay/accounts/wallet/wallet.py
  caver/klay/klay.py
Labels: WIP, enhancement, feature

#3 [documentation]Fix typo error
  README.md
Labels: documentation

#5 [hotfix] Git ignore for Python package
  .gitignore
Labels: hotfix

#4 [feature] Account Crypto, Hash function
  .gitignore
  caver/klay/accounts/account/__init__.py
  caver/klay/accounts/account/account.py
  caver/klay/accounts/accountKey/__init__.py
  caver/klay/accounts/accountKey/accountKeyPublic.py
  caver/klay/accounts/accountUtil/accountUtil.py
  caver/klay/accounts/accountUtil/bytes.py
  caver/klay/accounts/accountUtil/hashFunction.py
  caver/klay/accounts/accounts.py
  requirements.txt
  test.py
Labels: enhancement, feature

#6 [feature] blocks, Block Obejct
  caver/caver.py
  caver/klay/blocks/__init__.py
  caver/klay/blocks/block/__init__.py
  caver/klay/blocks/block/block.py
  caver/klay/blocks/blocks.py
  caver/klay/klay.py
  test.py
Labels: WIP, enhancement, feature

#10 [FIX] Fix CircleCI config error
  .circleci/config.yml
Labels: enhancement

#7 Block class 구조 변화, getBlockByHash 메소드 추가, test.py 테스트 코드 추가
  caver/klay/blocks/__init__.py
  caver/klay/blocks/block/__init__.py
  caver/klay/blocks/block/block.py
  caver/klay/blocks/blocks.py
  test.py
Labels: enhancement
